# Generated by Django 3.0.3 on 2020-03-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20190620_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=50)),
                ('length', models.CharField(max_length=10)),
                ('widht', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('wheel_base', models.CharField(max_length=10)),
                ('ground_clearance', models.CharField(max_length=10)),
                ('Boot_capacity', models.CharField(max_length=10)),
                ('Fuel_type', models.CharField(max_length=10)),
                ('Engine_displacement', models.CharField(max_length=10)),
                ('Engine_type', models.CharField(max_length=10)),
                ('Max_power', models.CharField(max_length=20)),
            ],
        ),
    ]
