# Generated by Django 3.0.3 on 2020-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_car_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_info',
            name='Boot_capacity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='Engine_displacement',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='Engine_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='Fuel_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='Max_power',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='ground_clearance',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='length',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='wheel_base',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car_info',
            name='widht',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
